<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class PosicionesUnidadesSeeder extends Seeder
{    public function run()
    {
        // Datos extraidos del Excel 'BD marzo 2026' (754 trabajadores)
        // Columnas I (Unidad Organizativa) y J (Posicion)

        $unidades = [
            'ALMACEN CENTRAL',
            'BRIGADA DE CABLE',
            'BRIGADA PRESURIZACION Y SOTERRADO',
            'BRIGADAS DE CABLE',
            'BRIGADAS DE LINEA',
            'BRIGADAS DE RECONSTRUCCION DE BAJANTES',
            'CASITA INFANTIL',
            'CENTRO DE ATENCION TELEF. PINAR DEL RIO',
            'CENTRO DE DIRECCION TERRITORIAL',
            'CENTRO DE FACTURACION',
            'CENTRO MULTISERV CONSOL. DEL SUR(3315 L',
            'CENTRO MULTISERVICIOS ALAMEDA',
            'CENTRO MULTISERVICIOS CALLE MARTI',
            'CENTRO MULTISERVICIOS HERMANOS CRUZ',
            'CENTRO MULTISERVICIOS PINAR DEL RIO',
            'CENTRO MULTISERVICIOS SANDINO (1 973 LS)',
            'CENTRO MULTISERVICIOS VIÑALES (3 714 LS)',
            'CENTRO OPERACION DEL CABLE COAXIAL',
            'CENTRO TELECOM ASOC GUANE (2 1010  LI)',
            'CENTRO TELECOM ASOC LA PALMA (1320  LI)',
            'CENTRO TELECOM ASOC LA PALMA (2 400 LI)',
            'CENTRO TELECOM ASOC LOS PALACIOS(3 780LI',
            'CENTRO TELECOM ASOC MANTUA (1016  LI)',
            'CENTRO TELECOM ASOC MINAS MATAHAMBR(1870',
            'CENTRO TELECOM ASOC SAN JUAN (1 500 LI)',
            'CENTRO TELECOM ASOC SAN LUIS (1 650 LI)',
            'CENTRO TELECOM ASOC VIÑALES (4 410 LI)',
            'CENTRO TELECOM PPAL  CONS.DEL SUR(2375 L',
            'CENTRO TELECOM PPAL CONS.DEL SUR(8 016LI',
            'CENTRO TELECOM PPAL P.DEL RIO(49 314 LI)',
            'CENTRO TELECOM PPAL SANDINO (5065 LI)',
            'COMERCIAL',
            'DEPARTAMENTO DE ECONOMIA',
            'DEPARTAMENTO DE LOGISTICA Y SERVICIOS',
            'DIVISION TERRITORIAL PINAR DEL RIO',
            'DPTO. CAPITAL HUMANO',
            'DPTO. COMERCIAL',
            'DPTO. COORDINACION GENERAL',
            'DPTO. DE INVERSIONES',
            'DPTO. LOGISTICA Y SERVICIOS',
            'DPTO. OPERACIONES DE RED',
            'DV TERRITORIAL PINAR DEL RIO',
            'ECONOMICO ADMINISTRATIVO',
            'FIBRA OPTICA',
            'GRUPO ADMINISTRACION DE LA RED',
            'GRUPO DE COMERCIALIZACIÓN COORPORATIVO',
            'GRUPO DE COMERCIALIZACION MASIVO',
            'GRUPO DE CONTABILIDAD',
            'GRUPO DE CONTROL, SEGURIDAD Y DEFENSA',
            'GRUPO DE FINANZAS',
            'GRUPO DE INSTALACION Y EJECUCION CIVIL',
            'GRUPO DE INTERVENCION TECNICA',
            'GRUPO DE LOGISTICA',
            'GRUPO DE LOGISTICA Y TALLERES',
            'GRUPO DE MARKETING',
            'GRUPO DE OPERACION Y MANTENIMIENTO',
            'GRUPO DE PLANEAMIENTO  CONTROL TEC. INV',
            'GRUPO DE PROYECTO',
            'GRUPO DE RED DE ACCESO',
            'GRUPO DE SERVICIOS GENERALES',
            'GRUPO DE SOPORTE COMERCIAL',
            'GRUPO DE SUPERVISIÓN',
            'GRUPO DE TRANSPORTE',
            'GRUPO SUPERVISION Y GESTION',
            'OFICINA COMERCIAL EMPRESAS',
            'OFICINA COMERCIAL GUANE (1435  LS)',
            'OFICINA COMERCIAL LA PALMA (2 377 LS)',
            'OFICINA COMERCIAL LOS PALACIOS (3 653 LS',
            'OFICINA COMERCIAL MANTUA (568 LS)',
            'OFICINA COMERCIAL MINAS (1 127 LS)',
            'OFICINA COMERCIAL PINAR DEL RIO(32 167LS',
            'OFICINA COMERCIAL SAN JUAN (2 113 LS)',
            'OFICINA COMERCIAL SAN LUIS (1 638 LS)',
            'OPERACION Y MANTENIMIENTO',
            'PLANTA EXTERIOR',
            'PLANTA INTERIOR',
            'RED DE ABONADOS',
            'SOPORTE INFORMATICO',
            'TALLER DE REPARACIONES',
            'TALLER DE TRANSPORTE',
            'TECNOLOGIAS DE LA INFORMACION',
            'UNIDAD DE CONTROL',
            'UNIDAD DE CONTROL DE LA OPERACION',
            'UNIDAD DE ENERGETICA, CLIMATIZAC. Y SPI',
            'UNIDAD DE PIZARRAS PRIVADAS',
            'UNIDAD DE REDES INALAMBRICAS',
            'UNIDAD DE SUPERVISION',
            'UNIDAD DE TRAFICO Y OPTIMIZACION',
            'UNIDAD DE TRANSMISION',
            'UNIDAD DIAGNOSTICO Y ASIST. TÉCNICA',
            'UNIDAD OPERATIVA',
        ];

        $posiciones = [
            ['nombre' => 'ACONDICIONADOR DE REGISTROS', 'alto_riesgo' => false, 'tipo_alto_riesgo' => null, 'subcategoria' => null],
            ['nombre' => 'ALBAÑIL "A"', 'alto_riesgo' => false, 'tipo_alto_riesgo' => null, 'subcategoria' => null],
            ['nombre' => 'ASESOR LEGAL "B" EN TELEMATICA', 'alto_riesgo' => false, 'tipo_alto_riesgo' => null, 'subcategoria' => null],
            ['nombre' => 'AUXILIAR DE LIMPIEZA', 'alto_riesgo' => false, 'tipo_alto_riesgo' => null, 'subcategoria' => null],
            ['nombre' => 'AUXILIAR GENERAL DE SERVICIOS', 'alto_riesgo' => false, 'tipo_alto_riesgo' => null, 'subcategoria' => null],
            ['nombre' => 'AUXILIAR PEDAGOGICA', 'alto_riesgo' => false, 'tipo_alto_riesgo' => null, 'subcategoria' => null],
            ['nombre' => 'AUXILIAR TECNICO', 'alto_riesgo' => false, 'tipo_alto_riesgo' => null, 'subcategoria' => null],
            ['nombre' => 'AYUDANTE', 'alto_riesgo' => false, 'tipo_alto_riesgo' => null, 'subcategoria' => null],
            ['nombre' => 'CHOFER "B"', 'alto_riesgo' => true, 'tipo_alto_riesgo' => 'chofer', 'subcategoria' => 'B'],
            ['nombre' => 'CHOFER "C"', 'alto_riesgo' => true, 'tipo_alto_riesgo' => 'chofer', 'subcategoria' => 'C'],
            ['nombre' => 'CHOFER "D"', 'alto_riesgo' => true, 'tipo_alto_riesgo' => 'chofer', 'subcategoria' => 'D'],
            ['nombre' => 'CHOFER DE OMNIBUS "C"', 'alto_riesgo' => true, 'tipo_alto_riesgo' => 'chofer', 'subcategoria' => 'C'],
            ['nombre' => 'CHOFER OPERADOR “C” DE GRUA CAMION', 'alto_riesgo' => true, 'tipo_alto_riesgo' => 'operador_grua', 'subcategoria' => null],
            ['nombre' => 'DEP. TRANSPORTADOR DE MERCANCIA', 'alto_riesgo' => false, 'tipo_alto_riesgo' => null, 'subcategoria' => null],
            ['nombre' => 'DESP. ORDENES PLANTA EXTERIOR', 'alto_riesgo' => false, 'tipo_alto_riesgo' => null, 'subcategoria' => null],
            ['nombre' => 'DIRECTOR TERRITORIAL', 'alto_riesgo' => false, 'tipo_alto_riesgo' => null, 'subcategoria' => null],
            ['nombre' => 'EDUCADORA', 'alto_riesgo' => false, 'tipo_alto_riesgo' => null, 'subcategoria' => null],
            ['nombre' => 'EJECUTIVO "A" EN TELEMATICA', 'alto_riesgo' => false, 'tipo_alto_riesgo' => null, 'subcategoria' => null],
            ['nombre' => 'EJECUTIVO "A" EN TELEMATICA (JB)', 'alto_riesgo' => false, 'tipo_alto_riesgo' => null, 'subcategoria' => null],
            ['nombre' => 'EJECUTIVO "B" DE CUENTAS', 'alto_riesgo' => false, 'tipo_alto_riesgo' => null, 'subcategoria' => null],
            ['nombre' => 'EJECUTIVO DE FACTURACION', 'alto_riesgo' => false, 'tipo_alto_riesgo' => null, 'subcategoria' => null],
            ['nombre' => 'EJECUTIVO DE PUNTO DE VENTA', 'alto_riesgo' => false, 'tipo_alto_riesgo' => null, 'subcategoria' => null],
            ['nombre' => 'EJECUTIVO DE PUNTO DE VENTA (EP)', 'alto_riesgo' => false, 'tipo_alto_riesgo' => null, 'subcategoria' => null],
            ['nombre' => 'ELECTRICISTA "A" AUTOMOTOR', 'alto_riesgo' => false, 'tipo_alto_riesgo' => null, 'subcategoria' => null],
            ['nombre' => 'ENCARGADO DE ALMACEN "C"', 'alto_riesgo' => false, 'tipo_alto_riesgo' => null, 'subcategoria' => null],
            ['nombre' => 'ESP. "B" AHORRO Y USO RAC. ENERGIA', 'alto_riesgo' => false, 'tipo_alto_riesgo' => null, 'subcategoria' => null],
            ['nombre' => 'ESP. "B" EN ABAST. TEC. MATERIAL', 'alto_riesgo' => false, 'tipo_alto_riesgo' => null, 'subcategoria' => null],
            ['nombre' => 'ESP. "B" EN CIENCIAS INFORMATICAS', 'alto_riesgo' => false, 'tipo_alto_riesgo' => null, 'subcategoria' => null],
            ['nombre' => 'ESP. "B" EN ECONOMIA DE ALMACENES', 'alto_riesgo' => false, 'tipo_alto_riesgo' => null, 'subcategoria' => null],
            ['nombre' => 'ESP. "B" EN GEST. DE REC. HUMANOS', 'alto_riesgo' => false, 'tipo_alto_riesgo' => null, 'subcategoria' => null],
            ['nombre' => 'ESP. "B" EN GEST. DE REC. HUMANOS (EP)', 'alto_riesgo' => false, 'tipo_alto_riesgo' => null, 'subcategoria' => null],
            ['nombre' => 'ESP. "B" EN GEST. DE RECURSOS HUMANOS', 'alto_riesgo' => false, 'tipo_alto_riesgo' => null, 'subcategoria' => null],
            ['nombre' => 'ESP. "B" EN GEST. ECONOMICA', 'alto_riesgo' => false, 'tipo_alto_riesgo' => null, 'subcategoria' => null],
            ['nombre' => 'ESP. "B" EN SEGUR. Y SALUD TRABAJO', 'alto_riesgo' => false, 'tipo_alto_riesgo' => null, 'subcategoria' => null],
            ['nombre' => 'ESP. "B" PARA LA DEFENSA Y DEFENSA CIVIL', 'alto_riesgo' => false, 'tipo_alto_riesgo' => null, 'subcategoria' => null],
            ['nombre' => 'ESP. "C" EN CIENCIAS INFORMATICAS', 'alto_riesgo' => false, 'tipo_alto_riesgo' => null, 'subcategoria' => null],
            ['nombre' => 'ESP. "C" EN TELEMATICA', 'alto_riesgo' => false, 'tipo_alto_riesgo' => null, 'subcategoria' => null],
            ['nombre' => 'ESP. "C" EN TELEMATICA (EP)', 'alto_riesgo' => false, 'tipo_alto_riesgo' => null, 'subcategoria' => null],
            ['nombre' => 'ESPEC. "B" DEL TRANSPORTE AUTOMOTOR', 'alto_riesgo' => false, 'tipo_alto_riesgo' => null, 'subcategoria' => null],
            ['nombre' => 'ESPEC. "B" EN OBRAS ARQUIT E INDUST', 'alto_riesgo' => false, 'tipo_alto_riesgo' => null, 'subcategoria' => null],
            ['nombre' => 'ESPEC. "B" EN PROTECC. AL CONSUMIDOR', 'alto_riesgo' => false, 'tipo_alto_riesgo' => null, 'subcategoria' => null],
            ['nombre' => 'ESPEC. "B" EN SISTEMAS DE GESTION', 'alto_riesgo' => false, 'tipo_alto_riesgo' => null, 'subcategoria' => null],
            ['nombre' => 'ESPEC. "B" GESTION DOCUMENTAL', 'alto_riesgo' => false, 'tipo_alto_riesgo' => null, 'subcategoria' => null],
            ['nombre' => 'ESPEC. "C" SISTEMA DIREC. TELECOM.', 'alto_riesgo' => false, 'tipo_alto_riesgo' => null, 'subcategoria' => null],
            ['nombre' => 'ESPEC. GRAL. "B" CIENCIA, TECNOL. INNOV', 'alto_riesgo' => false, 'tipo_alto_riesgo' => null, 'subcategoria' => null],
            ['nombre' => 'ESPECIALISTA "B" ASEGURAM. INGRESOS', 'alto_riesgo' => false, 'tipo_alto_riesgo' => null, 'subcategoria' => null],
            ['nombre' => 'ESPECIALISTA "B" EN CIBERSEGURIDAD', 'alto_riesgo' => false, 'tipo_alto_riesgo' => null, 'subcategoria' => null],
            ['nombre' => 'ESPECIALISTA "B" EN CIBERSEGURIDAD (EP)', 'alto_riesgo' => false, 'tipo_alto_riesgo' => null, 'subcategoria' => null],
            ['nombre' => 'ESPECIALISTA "B" EN CONTROL INTERNO', 'alto_riesgo' => false, 'tipo_alto_riesgo' => null, 'subcategoria' => null],
            ['nombre' => 'ESPECIALISTA "B" EN CONTROL TECNOL.', 'alto_riesgo' => false, 'tipo_alto_riesgo' => null, 'subcategoria' => null],
            ['nombre' => 'ESPECIALISTA "B" EN CUADROS', 'alto_riesgo' => false, 'tipo_alto_riesgo' => null, 'subcategoria' => null],
            ['nombre' => 'ESPECIALISTA "B" EN OBRAS DE INGENIERIA', 'alto_riesgo' => false, 'tipo_alto_riesgo' => null, 'subcategoria' => null],
            ['nombre' => 'ESPECIALISTA "C" COMERCIAL', 'alto_riesgo' => false, 'tipo_alto_riesgo' => null, 'subcategoria' => null],
            ['nombre' => 'ESPECIALISTA "C" EN COMUNICACION', 'alto_riesgo' => false, 'tipo_alto_riesgo' => null, 'subcategoria' => null],
            ['nombre' => 'EXPERTO EN TELEMATICA', 'alto_riesgo' => false, 'tipo_alto_riesgo' => null, 'subcategoria' => null],
            ['nombre' => 'GESTOR DE SERVICIOS', 'alto_riesgo' => false, 'tipo_alto_riesgo' => null, 'subcategoria' => null],
            ['nombre' => 'Integración: Posición por defecto', 'alto_riesgo' => false, 'tipo_alto_riesgo' => null, 'subcategoria' => null],
            ['nombre' => 'JEFE DE CENTRO', 'alto_riesgo' => false, 'tipo_alto_riesgo' => null, 'subcategoria' => null],
            ['nombre' => 'JEFE DE CENTRO DE TELEC. "A"', 'alto_riesgo' => false, 'tipo_alto_riesgo' => null, 'subcategoria' => null],
            ['nombre' => 'JEFE DE CENTRO DE TELEC. "B"', 'alto_riesgo' => false, 'tipo_alto_riesgo' => null, 'subcategoria' => null],
            ['nombre' => 'JEFE DE CENTRO DE TELEC. "C"', 'alto_riesgo' => false, 'tipo_alto_riesgo' => null, 'subcategoria' => null],
            ['nombre' => 'JEFE DE DEPARTAMENTO "B"', 'alto_riesgo' => false, 'tipo_alto_riesgo' => null, 'subcategoria' => null],
            ['nombre' => 'JEFE DE GRUPO', 'alto_riesgo' => false, 'tipo_alto_riesgo' => null, 'subcategoria' => null],
            ['nombre' => 'JEFE DE TALLER', 'alto_riesgo' => false, 'tipo_alto_riesgo' => null, 'subcategoria' => null],
            ['nombre' => 'JEFE DE UNIDAD', 'alto_riesgo' => false, 'tipo_alto_riesgo' => null, 'subcategoria' => null],
            ['nombre' => 'LINIERO "A"', 'alto_riesgo' => true, 'tipo_alto_riesgo' => 'liniero', 'subcategoria' => 'A'],
            ['nombre' => 'LINIERO "A" (JB)', 'alto_riesgo' => true, 'tipo_alto_riesgo' => 'liniero', 'subcategoria' => 'A'],
            ['nombre' => 'LINIERO "B"', 'alto_riesgo' => true, 'tipo_alto_riesgo' => 'liniero', 'subcategoria' => 'B'],
            ['nombre' => 'MECANICO "A" AUTOMOTOR', 'alto_riesgo' => false, 'tipo_alto_riesgo' => null, 'subcategoria' => null],
            ['nombre' => 'OP. "B" INSTAL. REPARADOR', 'alto_riesgo' => true, 'tipo_alto_riesgo' => 'operario_cables', 'subcategoria' => 'B'],
            ['nombre' => 'OP. "B" INSTAL. REPARADOR (JB)', 'alto_riesgo' => true, 'tipo_alto_riesgo' => 'operario_cables', 'subcategoria' => 'B'],
            ['nombre' => 'OP. "C" INSTAL. REPARADOR', 'alto_riesgo' => true, 'tipo_alto_riesgo' => 'operario_cables', 'subcategoria' => 'C'],
            ['nombre' => 'OP. TRAZA DE CABLE COAXIAL', 'alto_riesgo' => true, 'tipo_alto_riesgo' => 'operario_cables', 'subcategoria' => null],
            ['nombre' => 'OPERADOR GENERAL DE MTTO. Y REP.', 'alto_riesgo' => false, 'tipo_alto_riesgo' => null, 'subcategoria' => null],
            ['nombre' => 'OPERADOR GENERAL DE MTTO. Y REP. (JB)', 'alto_riesgo' => false, 'tipo_alto_riesgo' => null, 'subcategoria' => null],
            ['nombre' => 'OPERARIO "A" DE CABLE', 'alto_riesgo' => true, 'tipo_alto_riesgo' => 'operario_cables', 'subcategoria' => 'A'],
            ['nombre' => 'OPERARIO "A" DE CABLE (JB)', 'alto_riesgo' => true, 'tipo_alto_riesgo' => 'operario_cables', 'subcategoria' => 'A'],
            ['nombre' => 'OPERARIO "B" DE CABLE', 'alto_riesgo' => true, 'tipo_alto_riesgo' => 'operario_cables', 'subcategoria' => 'B'],
            ['nombre' => 'OPERARIO EN TELEMATICA', 'alto_riesgo' => false, 'tipo_alto_riesgo' => null, 'subcategoria' => null],
            ['nombre' => 'PROBADOR DE CABLE', 'alto_riesgo' => true, 'tipo_alto_riesgo' => 'operario_cables', 'subcategoria' => null],
            ['nombre' => 'RECEPCIONISTA', 'alto_riesgo' => false, 'tipo_alto_riesgo' => null, 'subcategoria' => null],
            ['nombre' => 'SECRETARIA EJECUTIVA "B"', 'alto_riesgo' => false, 'tipo_alto_riesgo' => null, 'subcategoria' => null],
            ['nombre' => 'SOLDADOR "A"', 'alto_riesgo' => false, 'tipo_alto_riesgo' => null, 'subcategoria' => null],
            ['nombre' => 'SUPERVISOR DE PLANTA EXTERIOR', 'alto_riesgo' => false, 'tipo_alto_riesgo' => null, 'subcategoria' => null],
            ['nombre' => 'TEC. "A" EN ECONOMIA Y MANIPUL. ALMAC.', 'alto_riesgo' => false, 'tipo_alto_riesgo' => null, 'subcategoria' => null],
            ['nombre' => 'TEC. "A" EN GEST. DE REC. HUMANOS', 'alto_riesgo' => false, 'tipo_alto_riesgo' => null, 'subcategoria' => null],
            ['nombre' => 'TEC. "A" EN GESTION ECONOMICA', 'alto_riesgo' => false, 'tipo_alto_riesgo' => null, 'subcategoria' => null],
            ['nombre' => 'TEC. EN CIENCIAS INFORMATICAS', 'alto_riesgo' => false, 'tipo_alto_riesgo' => null, 'subcategoria' => null],
            ['nombre' => 'TEC. EN CIENCIAS INFORMATICAS (EP)', 'alto_riesgo' => false, 'tipo_alto_riesgo' => null, 'subcategoria' => null],
            ['nombre' => 'TEC. EN PROT. FISICA Y SECR. ESTATAL', 'alto_riesgo' => false, 'tipo_alto_riesgo' => null, 'subcategoria' => null],
            ['nombre' => 'TECNICO "B" EN GEST COMERCIAL', 'alto_riesgo' => false, 'tipo_alto_riesgo' => null, 'subcategoria' => null],
            ['nombre' => 'TECNICO "B" EN TELEMATICA', 'alto_riesgo' => false, 'tipo_alto_riesgo' => null, 'subcategoria' => null],
            ['nombre' => 'TECNICO EN DIAGNOSTICO Y ASIST. TEC.', 'alto_riesgo' => false, 'tipo_alto_riesgo' => null, 'subcategoria' => null],
            ['nombre' => 'TECNICO EN SERVICIO SOCIAL N.S.', 'alto_riesgo' => false, 'tipo_alto_riesgo' => null, 'subcategoria' => null],
            ['nombre' => 'TECNICO EN SERVICIO SOCIAL T.M.', 'alto_riesgo' => false, 'tipo_alto_riesgo' => null, 'subcategoria' => null],
            ['nombre' => 'TORRERO "A"', 'alto_riesgo' => true, 'tipo_alto_riesgo' => 'torrero', 'subcategoria' => 'A'],
            ['nombre' => 'TORRERO "A" (JB)', 'alto_riesgo' => true, 'tipo_alto_riesgo' => 'torrero', 'subcategoria' => 'A'],
            ['nombre' => 'TORRERO "B"', 'alto_riesgo' => true, 'tipo_alto_riesgo' => 'torrero', 'subcategoria' => 'B'],
        ];

        foreach ($unidades as $nombre) {
            DB::table('unidades_organizativas')->updateOrInsert(
                ['nombre' => $nombre],
                ['nombre' => $nombre, 'updated_at' => now()]
            );
        }

        foreach ($posiciones as $p) {
            DB::table('posiciones')->updateOrInsert(
                ['nombre' => $p['nombre']],
                $p + ['updated_at' => now()]
            );
        }
    }
}

